version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "communication"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"

  graph:
    build: .
    ports:
      - 8080:8080
    environment:
      - PGDSN=postgresql://postgres:1234@postgres:5432/communication?sslmode=disable&timezone=UTC
      - PORT=:8080
    depends_on:
      - postgres
